In [20]:
import pandas as pd
import numpy as np

In [33]:
df = pd.read_csv('Joined Dataset.csv').drop_duplicates(subset = ['Contact Email','Contact Name','Client','Training'])
df

,Training,Contact Email,Contact Name,Client,Client ID,Account Manager,From Date
0,Prep 101 - 2020-10-01,abagael.matresse@brauninc.com,Abagael Matresse,Braun Inc,1200,Xiaoxuan Ma,31/12/2019
1,Prep 101 - 2020-10-01,abagail.macconnell@lakinllc.com,Abagail MacConnell,Lakin LLC,924,Lucy Stevenson,01/01/2019
2,Prep 101 - 2020-10-01,abagail.moodey@raynorinc.com,Abagail Moodey,Raynor Inc,444,Nancy Smith,01/07/2015
3,Prep 101 - 2020-10-01,abby.eager@paucekgroup.com,Abby Eager,Paucek Group,893,Nancy Smith,20/09/2018
4,Prep 101 - 2020-10-01,abelard.mechell@lehner.swiftanddickinson.com,Abelard Mechell,"Lehner, Swift and Dickinson",1323,Xiaoxuan Ma,31/12/2019
...,...,...,...,...,...,...,...
13618,Tableau 104 - 2020-09-17,zenia.antonin@marks-gulgowski.com,Zenia Antonin,Marks-Gulgowski,1022,Ezazul Islam,01/02/2018
13619,Tableau 104 - 2020-09-17,zia.easterling@turcotte-borer.com,Zia Easterling,Turcotte-Borer,1300,Lucy Stevenson,31/07/2019
13620,Tableau 104 - 2020-10-08,zolly.bonson@hudson.runolfsdottirandabbott.com,Zolly Bonson,"Hudson, Runolfsdottir and Abbott",1092,Oscar Adams,01/09/2018
13621,Tableau 104 - 2020-10-08,zolly.duxfield@ortiz.harrisandbrown.com,Zolly Duxfield,"Ortiz, Harris and Brown",1164,Oscar Adams,31/05/2018
13622,Tableau 104 - 2020-10-08,zora.bruntjen@gerlachgroup.com,Zora Bruntjen,Gerlach Group,2469,Xiaoxuan Ma,10/07/2020

In [29]:
df_newest_manager = df.sort_values(by = ['From Date']).groupby('Client')[['Client ID','Account Manager', 'From Date', 
                           ]].last().reset_index()
df_newest_manager

                            Client  Client ID Account Manager   From Date
0                Abbott-Runolfsson       1298    Ezazul Islam  02/09/2019
1                Abbott-Stiedemann        960      Mark Jones  01/09/2017
2                    Abbott-Stokes       1213     Xiaoxuan Ma  27/07/2020
3                    Abernathy LLC       1353     Xiaoxuan Ma  03/12/2019
4    Abernathy, Ledner and Stroman        425  Lucy Stevenson  25/11/2019
..                             ...        ...             ...         ...
522                      Yundt LLC       1167     Nancy Smith  04/02/2019
523                 Yundt and Sons        835     Xiaoxuan Ma  31/12/2019
524        Yundt, Reilly and Towne        426    Louisa James  01/07/2015
525               Ziemann and Sons       1203     Xiaoxuan Ma  30/06/2020
526                  Zulauf-Turner       1220    Louisa James  01/01/2019

[527 rows x 4 columns]

In [34]:
df_output = df.merge(df_newest_manager,how='left',on=['Client'])
df_output.drop(['Client ID_x','Account Manager_x','From Date_x'], axis=1, inplace=True)
df_output.rename(columns={'Account Manager_y':'Account Manager','Client ID_y':'Client ID','From Date_y':'From Date'}, inplace=True)
df_output

,Training,Contact Email,Contact Name,Client,Client ID,Account Manager,From Date
0,Prep 101 - 2020-10-01,abagael.matresse@brauninc.com,Abagael Matresse,Braun Inc,1200,Xiaoxuan Ma,31/12/2019
1,Prep 101 - 2020-10-01,abagail.macconnell@lakinllc.com,Abagail MacConnell,Lakin LLC,924,Lucy Stevenson,01/01/2019
2,Prep 101 - 2020-10-01,abagail.moodey@raynorinc.com,Abagail Moodey,Raynor Inc,444,Nancy Smith,01/07/2015
3,Prep 101 - 2020-10-01,abby.eager@paucekgroup.com,Abby Eager,Paucek Group,893,Nancy Smith,20/09/2018
4,Prep 101 - 2020-10-01,abelard.mechell@lehner.swiftanddickinson.com,Abelard Mechell,"Lehner, Swift and Dickinson",1323,Xiaoxuan Ma,31/12/2019
...,...,...,...,...,...,...,...
13523,Tableau 104 - 2020-09-17,zenia.antonin@marks-gulgowski.com,Zenia Antonin,Marks-Gulgowski,1022,Ezazul Islam,01/02/2018
13524,Tableau 104 - 2020-09-17,zia.easterling@turcotte-borer.com,Zia Easterling,Turcotte-Borer,1300,Lucy Stevenson,31/07/2019
13525,Tableau 104 - 2020-10-08,zolly.bonson@hudson.runolfsdottirandabbott.com,Zolly Bonson,"Hudson, Runolfsdottir and Abbott",1092,Oscar Adams,01/09/2018
13526,Tableau 104 - 2020-10-08,zolly.duxfield@ortiz.harrisandbrown.com,Zolly Duxfield,"Ortiz, Harris and Brown",1164,Oscar Adams,31/05/2018
13527,Tableau 104 - 2020-10-08,zora.bruntjen@gerlachgroup.com,Zora Bruntjen,Gerlach Group,2469,Xiaoxuan Ma,10/07/2020